### ISSUE TITLE
use different toolchain

### ISSUE THREAD

**Issue by limuy2022** [qqiangwu/cppship#53]
cppship is very perfect.And it solves many problems in cpp development.but i want to know if cppship can change toolchain easily such as unittest or packages manager.if it can't,do you want to finish it in cppship?

**Comment by qqiangwu** [comment]
unittest or benchmark toolchain can be customized in the future, just like Cargo. But I am not clear whether it should support multiple package managers. In my plan, it will only support conan2, git header-only packages, and git cppship packages, which might yield less package conflicts  and better cooperatability.  

Imaging the following case:

package1 in conan depends on boost in conan, package2 in vcpkg depends on boost in vcpkg, how do we resolve symbol conflicts, and version conflicts. Still to single package manager make such things simple.

Actually, I'm open to future designs, if you  do have some good ideas to solve the problem above, I will make them in cppship.

**Comment by limuy2022** [comment]
if we use different package managers in a project,it will not work well and maybe a lot of version problems.but i think it is not necessary to do that.my meaning is that use different package manager in different projects for example,vcpkg in project a,conan in project b.

**Comment by qqiangwu** [comment]
If we want to use cppship packages on git as dependencies, then things become difficult. If you only depends on vcpkg in your project, then it's okay, but our project will be less composable(say you find a cppship package on git, but it depends on conan, then you cannot use it without further investigation). I'm not sure if it is a good choice.

**Comment by limuy2022** [comment]
yes,you are right.using conan2 only is a good choice.it's my mistake.and to make things more simple,won't you make cppship support many knids of build systems such as xmake,and only use cmake?

**Comment by qqiangwu** [comment]
I'm not sure if I fully understand your problem.

If you use cppship only, you don't have to care about the underlying build tool. If you want your cppship packages be recognizable by mainstream c++ community, run `cppship cmake` to generate CMakeFiles.txt.

xmake is good enough, if you really need, write a script to translate a cppship package to xmake package, it won't be hard because cppship pacakges are highly structured and their dependencies are straightforward.

**Comment by limuy2022** [comment]
in fact,i just want to use some features in xmake,such as cpp module support.thank you for your answering

**Comment by qqiangwu** [comment]
> in fact,i just want to use some features in xmake,such as cpp module support.thank you for your answering

Definitely, I will add module support soon.
